# Generated by Django 3.1.1 on 2020-10-26 06:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='batch',
            field=models.CharField(default='A', max_length=5),
        ),
        migrations.AddField(
            model_name='student',
            name='section',
            field=models.CharField(max_length=5, null=True),
        ),
        migrations.AlterField(
            model_name='faculty',
            name='phone',
            field=models.CharField(max_length=11, null=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='phone',
            field=models.CharField(max_length=11, null=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='usn',
            field=models.CharField(default='1R', max_length=15, null=True, unique=True),
        ),
    ]
