# Generated by Django 3.1.4 on 2021-01-07 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectfinale',
            name='scrum_master',
            field=models.CharField(default='scrum master', max_length=100),
        ),
        migrations.AddField(
            model_name='projectphase1',
            name='scrum_master',
            field=models.CharField(default='scrum master', max_length=100),
        ),
        migrations.AddField(
            model_name='projectphase2',
            name='scrum_master',
            field=models.CharField(default='scrum master', max_length=100),
        ),
    ]
