# Generated by Django 3.1.1 on 2020-10-26 06:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_team'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='owner',
            field=models.CharField(default='Name + USN', max_length=555),
        ),
    ]
